spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    username: application
    password: development
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

